export interface CountryItem {
  id?: string;
  name: string;
  iso_code: string;
  phone_code: string;
  is_active?: number;
}

export const ALL_COUNTRIES_DATA: CountryItem[] = [
  { id: "AF", name: "Afghanistan", iso_code: "AF", phone_code: "+93", is_active: 1 },
  { id: "AL", name: "Albania", iso_code: "AL", phone_code: "+355", is_active: 1 },
  { id: "DZ", name: "Algeria", iso_code: "DZ", phone_code: "+213", is_active: 1 },
  { id: "AS", name: "American Samoa", iso_code: "AS", phone_code: "+1684", is_active: 1 },
  { id: "AD", name: "Andorra", iso_code: "AD", phone_code: "+376", is_active: 1 },
  { id: "AO", name: "Angola", iso_code: "AO", phone_code: "+244", is_active: 1 },
  { id: "AI", name: "Anguilla", iso_code: "AI", phone_code: "+1264", is_active: 1 },
  { id: "AQ", name: "Antarctica", iso_code: "AQ", phone_code: "+672", is_active: 1 },
  { id: "AG", name: "Antigua and Barbuda", iso_code: "AG", phone_code: "+1268", is_active: 1 },
  { id: "AR", name: "Argentina", iso_code: "AR", phone_code: "+54", is_active: 1 },
  { id: "AM", name: "Armenia", iso_code: "AM", phone_code: "+374", is_active: 1 },
  { id: "AW", name: "Aruba", iso_code: "AW", phone_code: "+297", is_active: 1 },
  { id: "AU", name: "Australia", iso_code: "AU", phone_code: "+61", is_active: 1 },
  { id: "AT", name: "Austria", iso_code: "AT", phone_code: "+43", is_active: 1 },
  { id: "AZ", name: "Azerbaijan", iso_code: "AZ", phone_code: "+994", is_active: 1 },
  { id: "BS", name: "Bahamas", iso_code: "BS", phone_code: "+1242", is_active: 1 },
  { id: "BH", name: "Bahrain", iso_code: "BH", phone_code: "+973", is_active: 1 },
  { id: "BD", name: "Bangladesh", iso_code: "BD", phone_code: "+880", is_active: 1 },
  { id: "BB", name: "Barbados", iso_code: "BB", phone_code: "+1246", is_active: 1 },
  { id: "BY", name: "Belarus", iso_code: "BY", phone_code: "+375", is_active: 1 },
  { id: "BE", name: "Belgium", iso_code: "BE", phone_code: "+32", is_active: 1 },
  { id: "BZ", name: "Belize", iso_code: "BZ", phone_code: "+501", is_active: 1 },
  { id: "BJ", name: "Benin", iso_code: "BJ", phone_code: "+229", is_active: 1 },
  { id: "BM", name: "Bermuda", iso_code: "BM", phone_code: "+1441", is_active: 1 },
  { id: "BT", name: "Bhutan", iso_code: "BT", phone_code: "+975", is_active: 1 },
  { id: "BO", name: "Bolivia", iso_code: "BO", phone_code: "+591", is_active: 1 },
  { id: "BA", name: "Bosnia and Herzegovina", iso_code: "BA", phone_code: "+387", is_active: 1 },
  { id: "BW", name: "Botswana", iso_code: "BW", phone_code: "+267", is_active: 1 },
  { id: "BV", name: "Bouvet Island", iso_code: "BV", phone_code: "+47", is_active: 1 },
  { id: "BR", name: "Brazil", iso_code: "BR", phone_code: "+55", is_active: 1 },
  { id: "IO", name: "British Indian Ocean Territory", iso_code: "IO", phone_code: "+246", is_active: 1 },
  { id: "VG", name: "British Virgin Islands", iso_code: "VG", phone_code: "+1284", is_active: 1 },
  { id: "BN", name: "Brunei", iso_code: "BN", phone_code: "+673", is_active: 1 },
  { id: "BG", name: "Bulgaria", iso_code: "BG", phone_code: "+359", is_active: 1 },
  { id: "BF", name: "Burkina Faso", iso_code: "BF", phone_code: "+226", is_active: 1 },
  { id: "BI", name: "Burundi", iso_code: "BI", phone_code: "+257", is_active: 1 },
  { id: "KH", name: "Cambodia", iso_code: "KH", phone_code: "+855", is_active: 1 },
  { id: "CM", name: "Cameroon", iso_code: "CM", phone_code: "+237", is_active: 1 },
  { id: "CA", name: "Canada", iso_code: "CA", phone_code: "+1", is_active: 1 },
  { id: "CV", name: "Cape Verde", iso_code: "CV", phone_code: "+238", is_active: 1 },
  { id: "BQ", name: "Caribbean Netherlands", iso_code: "BQ", phone_code: "+599", is_active: 1 },
  { id: "KY", name: "Cayman Islands", iso_code: "KY", phone_code: "+1345", is_active: 1 },
  { id: "CF", name: "Central African Republic", iso_code: "CF", phone_code: "+236", is_active: 1 },
  { id: "TD", name: "Chad", iso_code: "TD", phone_code: "+235", is_active: 1 },
  { id: "CL", name: "Chile", iso_code: "CL", phone_code: "+56", is_active: 1 },
  { id: "CN", name: "China", iso_code: "CN", phone_code: "+86", is_active: 1 },
  { id: "CX", name: "Christmas Island", iso_code: "CX", phone_code: "+61", is_active: 1 },
  { id: "CC", name: "Cocos (Keeling) Islands", iso_code: "CC", phone_code: "+61", is_active: 1 },
  { id: "CO", name: "Colombia", iso_code: "CO", phone_code: "+57", is_active: 1 },
  { id: "KM", name: "Comoros", iso_code: "KM", phone_code: "+269", is_active: 1 },
  { id: "CG", name: "Congo - Brazzaville", iso_code: "CG", phone_code: "+242", is_active: 1 },
  { id: "CD", name: "Congo - Kinshasa", iso_code: "CD", phone_code: "+243", is_active: 1 },
  { id: "CK", name: "Cook Islands", iso_code: "CK", phone_code: "+682", is_active: 1 },
  { id: "CR", name: "Costa Rica", iso_code: "CR", phone_code: "+506", is_active: 1 },
  { id: "HR", name: "Croatia", iso_code: "HR", phone_code: "+385", is_active: 1 },
  { id: "CU", name: "Cuba", iso_code: "CU", phone_code: "+53", is_active: 1 },
  { id: "CW", name: "Curaçao", iso_code: "CW", phone_code: "+599", is_active: 1 },
  { id: "CY", name: "Cyprus", iso_code: "CY", phone_code: "+357", is_active: 1 },
  { id: "CZ", name: "Czech Republic", iso_code: "CZ", phone_code: "+420", is_active: 1 },
  { id: "CI", name: "Côte d'Ivoire", iso_code: "CI", phone_code: "+225", is_active: 1 },
  { id: "DK", name: "Denmark", iso_code: "DK", phone_code: "+45", is_active: 1 },
  { id: "DJ", name: "Djibouti", iso_code: "DJ", phone_code: "+253", is_active: 1 },
  { id: "DM", name: "Dominica", iso_code: "DM", phone_code: "+1767", is_active: 1 },
  { id: "DO", name: "Dominican Republic", iso_code: "DO", phone_code: "+1809", is_active: 1 },
  { id: "EC", name: "Ecuador", iso_code: "EC", phone_code: "+593", is_active: 1 },
  { id: "EG", name: "Egypt", iso_code: "EG", phone_code: "+20", is_active: 1 },
  { id: "SV", name: "El Salvador", iso_code: "SV", phone_code: "+503", is_active: 1 },
  { id: "GQ", name: "Equatorial Guinea", iso_code: "GQ", phone_code: "+240", is_active: 1 },
  { id: "ER", name: "Eritrea", iso_code: "ER", phone_code: "+291", is_active: 1 },
  { id: "EE", name: "Estonia", iso_code: "EE", phone_code: "+372", is_active: 1 },
  { id: "SZ", name: "Eswatini", iso_code: "SZ", phone_code: "+268", is_active: 1 },
  { id: "ET", name: "Ethiopia", iso_code: "ET", phone_code: "+251", is_active: 1 },
  { id: "FK", name: "Falkland Islands", iso_code: "FK", phone_code: "+500", is_active: 1 },
  { id: "FO", name: "Faroe Islands", iso_code: "FO", phone_code: "+298", is_active: 1 },
  { id: "FJ", name: "Fiji", iso_code: "FJ", phone_code: "+679", is_active: 1 },
  { id: "FI", name: "Finland", iso_code: "FI", phone_code: "+358", is_active: 1 },
  { id: "FR", name: "France", iso_code: "FR", phone_code: "+33", is_active: 1 },
  { id: "GF", name: "French Guiana", iso_code: "GF", phone_code: "+594", is_active: 1 },
  { id: "PF", name: "French Polynesia", iso_code: "PF", phone_code: "+689", is_active: 1 },
  { id: "TF", name: "French Southern Territories", iso_code: "TF", phone_code: "+262", is_active: 1 },
  { id: "GA", name: "Gabon", iso_code: "GA", phone_code: "+241", is_active: 1 },
  { id: "GM", name: "Gambia", iso_code: "GM", phone_code: "+220", is_active: 1 },
  { id: "GE", name: "Georgia", iso_code: "GE", phone_code: "+995", is_active: 1 },
  { id: "DE", name: "Germany", iso_code: "DE", phone_code: "+49", is_active: 1 },
  { id: "GH", name: "Ghana", iso_code: "GH", phone_code: "+233", is_active: 1 },
  { id: "GI", name: "Gibraltar", iso_code: "GI", phone_code: "+350", is_active: 1 },
  { id: "GR", name: "Greece", iso_code: "GR", phone_code: "+30", is_active: 1 },
  { id: "GL", name: "Greenland", iso_code: "GL", phone_code: "+299", is_active: 1 },
  { id: "GD", name: "Grenada", iso_code: "GD", phone_code: "+1473", is_active: 1 },
  { id: "GP", name: "Guadeloupe", iso_code: "GP", phone_code: "+590", is_active: 1 },
  { id: "GU", name: "Guam", iso_code: "GU", phone_code: "+1671", is_active: 1 },
  { id: "GT", name: "Guatemala", iso_code: "GT", phone_code: "+502", is_active: 1 },
  { id: "GG", name: "Guernsey", iso_code: "GG", phone_code: "+44", is_active: 1 },
  { id: "GN", name: "Guinea", iso_code: "GN", phone_code: "+224", is_active: 1 },
  { id: "GW", name: "Guinea-Bissau", iso_code: "GW", phone_code: "+245", is_active: 1 },
  { id: "GY", name: "Guyana", iso_code: "GY", phone_code: "+592", is_active: 1 },
  { id: "HT", name: "Haiti", iso_code: "HT", phone_code: "+509", is_active: 1 },
  { id: "HM", name: "Heard & McDonald Islands", iso_code: "HM", phone_code: "+672", is_active: 1 },
  { id: "HN", name: "Honduras", iso_code: "HN", phone_code: "+504", is_active: 1 },
  { id: "HK", name: "Hong Kong", iso_code: "HK", phone_code: "+852", is_active: 1 },
  { id: "HU", name: "Hungary", iso_code: "HU", phone_code: "+36", is_active: 1 },
  { id: "IS", name: "Iceland", iso_code: "IS", phone_code: "+354", is_active: 1 },
  { id: "IN", name: "India", iso_code: "IN", phone_code: "+91", is_active: 1 },
  { id: "ID", name: "Indonesia", iso_code: "ID", phone_code: "+62", is_active: 1 },
  { id: "IR", name: "Iran", iso_code: "IR", phone_code: "+98", is_active: 1 },
  { id: "IQ", name: "Iraq", iso_code: "IQ", phone_code: "+964", is_active: 1 },
  { id: "IE", name: "Ireland", iso_code: "IE", phone_code: "+353", is_active: 1 },
  { id: "IM", name: "Isle of Man", iso_code: "IM", phone_code: "+44", is_active: 1 },
  { id: "IL", name: "Israel", iso_code: "IL", phone_code: "+972", is_active: 1 },
  { id: "IT", name: "Italy", iso_code: "IT", phone_code: "+39", is_active: 1 },
  { id: "JM", name: "Jamaica", iso_code: "JM", phone_code: "+1876", is_active: 1 },
  { id: "JP", name: "Japan", iso_code: "JP", phone_code: "+81", is_active: 1 },
  { id: "JE", name: "Jersey", iso_code: "JE", phone_code: "+44", is_active: 1 },
  { id: "JO", name: "Jordan", iso_code: "JO", phone_code: "+962", is_active: 1 },
  { id: "KZ", name: "Kazakhstan", iso_code: "KZ", phone_code: "+7", is_active: 1 },
  { id: "KE", name: "Kenya", iso_code: "KE", phone_code: "+254", is_active: 1 },
  { id: "KI", name: "Kiribati", iso_code: "KI", phone_code: "+686", is_active: 1 },
  { id: "XK", name: "Kosovo", iso_code: "XK", phone_code: "+383", is_active: 1 },
  { id: "KW", name: "Kuwait", iso_code: "KW", phone_code: "+965", is_active: 1 },
  { id: "KG", name: "Kyrgyzstan", iso_code: "KG", phone_code: "+996", is_active: 1 },
  { id: "LA", name: "Laos", iso_code: "LA", phone_code: "+856", is_active: 1 },
  { id: "LV", name: "Latvia", iso_code: "LV", phone_code: "+371", is_active: 1 },
  { id: "LB", name: "Lebanon", iso_code: "LB", phone_code: "+961", is_active: 1 },
  { id: "LS", name: "Lesotho", iso_code: "LS", phone_code: "+266", is_active: 1 },
  { id: "LR", name: "Liberia", iso_code: "LR", phone_code: "+231", is_active: 1 },
  { id: "LY", name: "Libya", iso_code: "LY", phone_code: "+218", is_active: 1 },
  { id: "LI", name: "Liechtenstein", iso_code: "LI", phone_code: "+423", is_active: 1 },
  { id: "LT", name: "Lithuania", iso_code: "LT", phone_code: "+370", is_active: 1 },
  { id: "LU", name: "Luxembourg", iso_code: "LU", phone_code: "+352", is_active: 1 },
  { id: "MO", name: "Macao", iso_code: "MO", phone_code: "+853", is_active: 1 },
  { id: "MG", name: "Madagascar", iso_code: "MG", phone_code: "+261", is_active: 1 },
  { id: "MW", name: "Malawi", iso_code: "MW", phone_code: "+265", is_active: 1 },
  { id: "MY", name: "Malaysia", iso_code: "MY", phone_code: "+60", is_active: 1 },
  { id: "MV", name: "Maldives", iso_code: "MV", phone_code: "+960", is_active: 1 },
  { id: "ML", name: "Mali", iso_code: "ML", phone_code: "+223", is_active: 1 },
  { id: "MT", name: "Malta", iso_code: "MT", phone_code: "+356", is_active: 1 },
  { id: "MH", name: "Marshall Islands", iso_code: "MH", phone_code: "+692", is_active: 1 },
  { id: "MQ", name: "Martinique", iso_code: "MQ", phone_code: "+596", is_active: 1 },
  { id: "MR", name: "Mauritania", iso_code: "MR", phone_code: "+222", is_active: 1 },
  { id: "MU", name: "Mauritius", iso_code: "MU", phone_code: "+230", is_active: 1 },
  { id: "YT", name: "Mayotte", iso_code: "YT", phone_code: "+262", is_active: 1 },
  { id: "MX", name: "Mexico", iso_code: "MX", phone_code: "+52", is_active: 1 },
  { id: "FM", name: "Micronesia", iso_code: "FM", phone_code: "+691", is_active: 1 },
  { id: "MD", name: "Moldova", iso_code: "MD", phone_code: "+373", is_active: 1 },
  { id: "MC", name: "Monaco", iso_code: "MC", phone_code: "+377", is_active: 1 },
  { id: "MN", name: "Mongolia", iso_code: "MN", phone_code: "+976", is_active: 1 },
  { id: "ME", name: "Montenegro", iso_code: "ME", phone_code: "+382", is_active: 1 },
  { id: "MS", name: "Montserrat", iso_code: "MS", phone_code: "+1664", is_active: 1 },
  { id: "MA", name: "Morocco", iso_code: "MA", phone_code: "+212", is_active: 1 },
  { id: "MZ", name: "Mozambique", iso_code: "MZ", phone_code: "+258", is_active: 1 },
  { id: "MM", name: "Myanmar (Burma)", iso_code: "MM", phone_code: "+95", is_active: 1 },
  { id: "NA", name: "Namibia", iso_code: "NA", phone_code: "+264", is_active: 1 },
  { id: "NR", name: "Nauru", iso_code: "NR", phone_code: "+674", is_active: 1 },
  { id: "NP", name: "Nepal", iso_code: "NP", phone_code: "+977", is_active: 1 },
  { id: "NL", name: "Netherlands", iso_code: "NL", phone_code: "+31", is_active: 1 },
  { id: "NC", name: "New Caledonia", iso_code: "NC", phone_code: "+687", is_active: 1 },
  { id: "NZ", name: "New Zealand", iso_code: "NZ", phone_code: "+64", is_active: 1 },
  { id: "NI", name: "Nicaragua", iso_code: "NI", phone_code: "+505", is_active: 1 },
  { id: "NE", name: "Niger", iso_code: "NE", phone_code: "+227", is_active: 1 },
  { id: "NG", name: "Nigeria", iso_code: "NG", phone_code: "+234", is_active: 1 },
  { id: "NU", name: "Niue", iso_code: "NU", phone_code: "+683", is_active: 1 },
  { id: "NF", name: "Norfolk Island", iso_code: "NF", phone_code: "+672", is_active: 1 },
  { id: "KP", name: "North Korea", iso_code: "KP", phone_code: "+850", is_active: 1 },
  { id: "MK", name: "North Macedonia", iso_code: "MK", phone_code: "+389", is_active: 1 },
  { id: "MP", name: "Northern Mariana Islands", iso_code: "MP", phone_code: "+1670", is_active: 1 },
  { id: "NO", name: "Norway", iso_code: "NO", phone_code: "+47", is_active: 1 },
  { id: "OM", name: "Oman", iso_code: "OM", phone_code: "+968", is_active: 1 },
  { id: "PK", name: "Pakistan", iso_code: "PK", phone_code: "+92", is_active: 1 },
  { id: "PW", name: "Palau", iso_code: "PW", phone_code: "+680", is_active: 1 },
  { id: "PS", name: "Palestine", iso_code: "PS", phone_code: "+970", is_active: 1 },
  { id: "PA", name: "Panama", iso_code: "PA", phone_code: "+507", is_active: 1 },
  { id: "PG", name: "Papua New Guinea", iso_code: "PG", phone_code: "+675", is_active: 1 },
  { id: "PY", name: "Paraguay", iso_code: "PY", phone_code: "+595", is_active: 1 },
  { id: "PE", name: "Peru", iso_code: "PE", phone_code: "+51", is_active: 1 },
  { id: "PH", name: "Philippines", iso_code: "PH", phone_code: "+63", is_active: 1 },
  { id: "PN", name: "Pitcairn Islands", iso_code: "PN", phone_code: "+64", is_active: 1 },
  { id: "PL", name: "Poland", iso_code: "PL", phone_code: "+48", is_active: 1 },
  { id: "PT", name: "Portugal", iso_code: "PT", phone_code: "+351", is_active: 1 },
  { id: "PR", name: "Puerto Rico", iso_code: "PR", phone_code: "+1787", is_active: 1 },
  { id: "QA", name: "Qatar", iso_code: "QA", phone_code: "+974", is_active: 1 },
  { id: "RO", name: "Romania", iso_code: "RO", phone_code: "+40", is_active: 1 },
  { id: "RU", name: "Russia", iso_code: "RU", phone_code: "+7", is_active: 1 },
  { id: "RW", name: "Rwanda", iso_code: "RW", phone_code: "+250", is_active: 1 },
  { id: "RE", name: "Réunion", iso_code: "RE", phone_code: "+262", is_active: 1 },
  { id: "BL", name: "Saint Barthélemy", iso_code: "BL", phone_code: "+590", is_active: 1 },
  { id: "SH", name: "Saint Helena", iso_code: "SH", phone_code: "+290", is_active: 1 },
  { id: "KN", name: "Saint Kitts and Nevis", iso_code: "KN", phone_code: "+1869", is_active: 1 },
  { id: "LC", name: "Saint Lucia", iso_code: "LC", phone_code: "+1758", is_active: 1 },
  { id: "MF", name: "Saint Martin", iso_code: "MF", phone_code: "+590", is_active: 1 },
  { id: "PM", name: "Saint Pierre and Miquelon", iso_code: "PM", phone_code: "+508", is_active: 1 },
  { id: "VC", name: "Saint Vincent & Grenadines", iso_code: "VC", phone_code: "+1784", is_active: 1 },
  { id: "WS", name: "Samoa", iso_code: "WS", phone_code: "+685", is_active: 1 },
  { id: "SM", name: "San Marino", iso_code: "SM", phone_code: "+378", is_active: 1 },
  { id: "ST", name: "São Tomé & Príncipe", iso_code: "ST", phone_code: "+239", is_active: 1 },
  { id: "SA", name: "Saudi Arabia", iso_code: "SA", phone_code: "+966", is_active: 1 },
  { id: "SN", name: "Senegal", iso_code: "SN", phone_code: "+221", is_active: 1 },
  { id: "RS", name: "Serbia", iso_code: "RS", phone_code: "+381", is_active: 1 },
  { id: "SC", name: "Seychelles", iso_code: "SC", phone_code: "+248", is_active: 1 },
  { id: "SL", name: "Sierra Leone", iso_code: "SL", phone_code: "+232", is_active: 1 },
  { id: "SG", name: "Singapore", iso_code: "SG", phone_code: "+65", is_active: 1 },
  { id: "SX", name: "Sint Maarten", iso_code: "SX", phone_code: "+1721", is_active: 1 },
  { id: "SK", name: "Slovakia", iso_code: "SK", phone_code: "+421", is_active: 1 },
  { id: "SI", name: "Slovenia", iso_code: "SI", phone_code: "+386", is_active: 1 },
  { id: "SB", name: "Solomon Islands", iso_code: "SB", phone_code: "+677", is_active: 1 },
  { id: "SO", name: "Somalia", iso_code: "SO", phone_code: "+252", is_active: 1 },
  { id: "ZA", name: "South Africa", iso_code: "ZA", phone_code: "+27", is_active: 1 },
  { id: "GS", name: "South Georgia & South Sandwich Islands", iso_code: "GS", phone_code: "+500", is_active: 1 },
  { id: "KR", name: "South Korea", iso_code: "KR", phone_code: "+82", is_active: 1 },
  { id: "SS", name: "South Sudan", iso_code: "SS", phone_code: "+211", is_active: 1 },
  { id: "ES", name: "Spain", iso_code: "ES", phone_code: "+34", is_active: 1 },
  { id: "LK", name: "Sri Lanka", iso_code: "LK", phone_code: "+94", is_active: 1 },
  { id: "SD", name: "Sudan", iso_code: "SD", phone_code: "+249", is_active: 1 },
  { id: "SR", name: "Suriname", iso_code: "SR", phone_code: "+597", is_active: 1 },
  { id: "SJ", name: "Svalbard & Jan Mayen", iso_code: "SJ", phone_code: "+47", is_active: 1 },
  { id: "SE", name: "Sweden", iso_code: "SE", phone_code: "+46", is_active: 1 },
  { id: "CH", name: "Switzerland", iso_code: "CH", phone_code: "+41", is_active: 1 },
  { id: "SY", name: "Syria", iso_code: "SY", phone_code: "+963", is_active: 1 },
  { id: "TW", name: "Taiwan", iso_code: "TW", phone_code: "+886", is_active: 1 },
  { id: "TJ", name: "Tajikistan", iso_code: "TJ", phone_code: "+992", is_active: 1 },
  { id: "TZ", name: "Tanzania", iso_code: "TZ", phone_code: "+255", is_active: 1 },
  { id: "TH", name: "Thailand", iso_code: "TH", phone_code: "+66", is_active: 1 },
  { id: "TL", name: "Timor-Leste", iso_code: "TL", phone_code: "+670", is_active: 1 },
  { id: "TG", name: "Togo", iso_code: "TG", phone_code: "+228", is_active: 1 },
  { id: "TK", name: "Tokelau", iso_code: "TK", phone_code: "+690", is_active: 1 },
  { id: "TO", name: "Tonga", iso_code: "TO", phone_code: "+676", is_active: 1 },
  { id: "TT", name: "Trinidad and Tobago", iso_code: "TT", phone_code: "+1868", is_active: 1 },
  { id: "TN", name: "Tunisia", iso_code: "TN", phone_code: "+216", is_active: 1 },
  { id: "TR", name: "Turkey", iso_code: "TR", phone_code: "+90", is_active: 1 },
  { id: "TM", name: "Turkmenistan", iso_code: "TM", phone_code: "+993", is_active: 1 },
  { id: "TC", name: "Turks & Caicos Islands", iso_code: "TC", phone_code: "+1649", is_active: 1 },
  { id: "TV", name: "Tuvalu", iso_code: "TV", phone_code: "+688", is_active: 1 },
  { id: "UM", name: "U.S. Outlying Islands", iso_code: "UM", phone_code: "+1", is_active: 1 },
  { id: "VI", name: "U.S. Virgin Islands", iso_code: "VI", phone_code: "+1340", is_active: 1 },
  { id: "UG", name: "Uganda", iso_code: "UG", phone_code: "+256", is_active: 1 },
  { id: "UA", name: "Ukraine", iso_code: "UA", phone_code: "+380", is_active: 1 },
  { id: "AE", name: "United Arab Emirates", iso_code: "AE", phone_code: "+971", is_active: 1 },
  { id: "GB", name: "United Kingdom", iso_code: "GB", phone_code: "+44", is_active: 1 },
  { id: "US", name: "United States", iso_code: "US", phone_code: "+1", is_active: 1 },
  { id: "UY", name: "Uruguay", iso_code: "UY", phone_code: "+598", is_active: 1 },
  { id: "UZ", name: "Uzbekistan", iso_code: "UZ", phone_code: "+998", is_active: 1 },
  { id: "VU", name: "Vanuatu", iso_code: "VU", phone_code: "+678", is_active: 1 },
  { id: "VA", name: "Vatican City", iso_code: "VA", phone_code: "+39", is_active: 1 },
  { id: "VE", name: "Venezuela", iso_code: "VE", phone_code: "+58", is_active: 1 },
  { id: "VN", name: "Vietnam", iso_code: "VN", phone_code: "+84", is_active: 1 },
  { id: "WF", name: "Wallis & Futuna", iso_code: "WF", phone_code: "+681", is_active: 1 },
  { id: "EH", name: "Western Sahara", iso_code: "EH", phone_code: "+212", is_active: 1 },
  { id: "YE", name: "Yemen", iso_code: "YE", phone_code: "+967", is_active: 1 },
  { id: "ZM", name: "Zambia", iso_code: "ZM", phone_code: "+260", is_active: 1 },
  { id: "ZW", name: "Zimbabwe", iso_code: "ZW", phone_code: "+263", is_active: 1 },
  { id: "AX", name: "Åland Islands", iso_code: "AX", phone_code: "+358", is_active: 1 }
];
